global:
  scrape_interval: 15s

scrape_configs:
  - job_name: employee-management
    metrics_path: /actuator/prometheus
    basic_auth:
      username: user
      password: User123
    static_configs:
      - targets: ['employee-app:8089']