package com.example.employeemanagement.integration;

import com.example.employeemanagement.entity.Employee;
import com.example.employeemanagement.repository.EmployeeRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.transaction.annotation.Transactional;

import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * INTEGRATION TEST (Phase 3) = test the FULL application together.
 *
 * What is REAL (not mocked):
 *   - Spring Boot context starts
 *   - EmployeeController
 *   - EmployeeServiceImpl
 *   - EmployeeRepository
 *   - H2 in-memory database (application-test.properties)
 *   - GlobalExceptionHandler
 *   - Spring Security (we send Basic Auth)
 *
 * What is NOT used:
 *   - MySQL, Redis, Zipkin (disabled in test profile)
 *
 * Difference from previous phases:
 *   Phase 1 → mocked repository, tested service only
 *   Phase 2 → mocked service, tested controller HTTP only
 *   Phase 3 → everything connected, end-to-end like Postman + real DB
 */
@SpringBootTest // starts full Spring application
@AutoConfigureMockMvc // gives MockMvc for HTTP calls
@ActiveProfiles("test") // loads application-test.properties (H2)
@Transactional // rolls back DB changes after each test (clean slate every time)
class EmployeeIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    /**
     * Real repository — we can use this to verify data was actually saved in H2.
     */
    @Autowired
    private EmployeeRepository employeeRepository;

    private Employee newEmployee;

    @BeforeEach
    void setUp() {
        // employee sent in POST body (no id — DB generates it)
        newEmployee = Employee.builder()
                .firstName("Asta")
                .lastName("Black")
                .email("asta@email.com")
                .department("Engineering")
                .salary(50000.0)
                .build();
    }

    // ═══════════════════════════════════════════════════════════
    // FULL CRUD FLOW — the most important integration test
    // ═══════════════════════════════════════════════════════════

    @Test
    @DisplayName("Integration - full CRUD: create → read → update → delete")
    void fullCrudFlow() throws Exception {
        // ── CREATE ──
        MvcResult createResult = mockMvc.perform(
                        post("/api/employees")
                                .with(httpBasic("user", "User123")) // Spring Security login
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(objectMapper.writeValueAsString(newEmployee))
                )
                .andExpect(status().isCreated()) // 201
                .andExpect(jsonPath("$.email").value("asta@email.com"))
                .andReturn();

        // read id from response JSON (generated by database)
        Employee created = objectMapper.readValue(
                createResult.getResponse().getContentAsString(),
                Employee.class
        );
        Long employeeId = created.getId();
        assertNotNull(employeeId);

        // verify row exists in real H2 database
        assertTrue(employeeRepository.findById(employeeId).isPresent());

        // ── READ BY ID ──
        mockMvc.perform(
                        get("/api/employees/" + employeeId)
                                .with(httpBasic("user", "User123"))
                )
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.firstName").value("Asta"));

        // ── UPDATE ──
        Employee updateRequest = Employee.builder()
                .firstName("Yuno")
                .lastName("Black")
                .email("yuno@email.com")
                .department("HR")
                .salary(60000.0)
                .build();

        mockMvc.perform(
                        put("/api/employees/" + employeeId)
                                .with(httpBasic("user", "User123"))
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(objectMapper.writeValueAsString(updateRequest))
                )
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.firstName").value("Yuno"))
                .andExpect(jsonPath("$.department").value("HR"));

        // ── DELETE ──
        mockMvc.perform(
                        delete("/api/employees/" + employeeId)
                                .with(httpBasic("user", "User123"))
                )
                .andExpect(status().isOk())
                .andExpect(content().string("Employee deleted successfully"));

        // ── READ AFTER DELETE → 404 ──
        mockMvc.perform(
                        get("/api/employees/" + employeeId)
                                .with(httpBasic("user", "User123"))
                )
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.status").value(404));
    }

    // ═══════════════════════════════════════════════════════════
    // GET ALL
    // ═══════════════════════════════════════════════════════════

    @Test
    @DisplayName("Integration - GET all returns saved employees")
    void getAllEmployees_returnsSavedEmployees() throws Exception {
        // save directly via repository to set up data
        employeeRepository.save(newEmployee);

        Employee second = Employee.builder()
                .firstName("Yuno")
                .lastName("Black")
                .email("yuno@email.com")
                .department("HR")
                .salary(45000.0)
                .build();
        employeeRepository.save(second);

        mockMvc.perform(
                        get("/api/employees")
                                .with(httpBasic("user", "User123"))
                )
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", hasSize(2))) // array length = 2
                .andExpect(jsonPath("$[*].email", containsInAnyOrder("asta@email.com", "yuno@email.com")));
    }

    // ═══════════════════════════════════════════════════════════
    // VALIDATION & ERRORS
    // ═══════════════════════════════════════════════════════════

    @Test
    @DisplayName("Integration - POST with invalid email returns 400")
    void createEmployee_invalidEmail_returns400() throws Exception {
        newEmployee.setEmail("bad-email");

        mockMvc.perform(
                        post("/api/employees")
                                .with(httpBasic("user", "User123"))
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(objectMapper.writeValueAsString(newEmployee))
                )
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error").value("Validation Failed"));
    }

    @Test
    @DisplayName("Integration - GET without auth returns 401 Unauthorized")
    void getEmployees_withoutAuth_returns401() throws Exception {
        // no httpBasic() → security blocks request
        mockMvc.perform(get("/api/employees"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    @DisplayName("Integration - GET non-existing id returns 404")
    void getEmployeeById_notFound_returns404() throws Exception {
        mockMvc.perform(
                        get("/api/employees/9999")
                                .with(httpBasic("user", "User123"))
                )
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.message", containsString("9999")));
    }

    @Test
    @DisplayName("Integration - duplicate email returns 500 (current behaviour)")
    void createEmployee_duplicateEmail_returns500() throws Exception {
        // first create succeeds
        mockMvc.perform(
                        post("/api/employees")
                                .with(httpBasic("user", "User123"))
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(objectMapper.writeValueAsString(newEmployee))
                )
                .andExpect(status().isCreated());

        // second create with same email fails
        // Note: IllegalArgumentException is handled by generic handler → 500
        // You can later add a dedicated handler and change this to 409 Conflict
        mockMvc.perform(
                        post("/api/employees")
                                .with(httpBasic("user", "User123"))
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(objectMapper.writeValueAsString(newEmployee))
                )
                .andExpect(status().isInternalServerError());
    }
}
