apiVersion: v1
kind: Service
metadata:
  name: employee-app
  namespace: employee-management
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30080
