apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
  namespace: employee-management
  labels:
    app: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: employee-management:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/employeedb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_CACHE_TYPE
              value: redis
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin:9411/api/v2/spans
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
          readinessProbe:
            tcpSocket:
              port: 8089
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8089
            initialDelaySeconds: 60
            periodSeconds: 15
