apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: employee-management
spec:                        #    Just like "redis" hostname in Compose!
  selector:
    app: redis               # Send traffic to Pods labeled "app: redis"
  ports:
  - port: 6379               # Port other services connect to
    targetPort: 6379         # Port on the container